lib/router/router.dart
lib/router/router.gr.dart
lib/screens/root.dart

Provide 'name' attribute to dummy route.

Fix route for search page.

---

lib/components/episode_list.dart
lib/env/env.dart
lib/router/router.dart
lib/router/router.gr.dart
lib/screens/search/search_results_page.dart

Fix episode navigation,
On search result page, hide the keyboard when user starts to scroll through the results.

Fix episode navigation, Hide keyboard on drag in search result page

---

external_projects/bccm_player/example/pubspec.lock
lib/components/default_grid_section.dart
pubspec.lock

Manually specify the type to map.

Specify type in map

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
ios/Runner/Info-Debug-dev.plist
ios/Runner/Info-Debug-prod.plist
ios/Runner/Info-Debug-v4_dev.plist
ios/Runner/Info-Debug-v4_prod.plist
ios/Runner/Info-Profile-dev.plist
ios/Runner/Info-Profile-prod.plist
ios/Runner/Info-Profile-v4_dev.plist
ios/Runner/Info-Profile-v4_prod.plist
ios/Runner/Info-Release-dev.plist
ios/Runner/Info-Release-prod.plist
ios/Runner/Info-Release-v4_dev.plist
ios/Runner/Info-Release-v4_prod.plist
ios/Runner/Runner.entitlements
lib/env/env.dart
lib/main.dart
lib/router/special_routes_guard.dart
lib/screens/episode.dart
lib/screens/home.dart
pubspec.yaml
web/index.html
web/manifest.json

Includes deep links and share to bcc.media.

Rename to bcc media

---

lib/helpers/custom_transitions.dart

Swipe from left to right to navigate back.

Swipe from left to right to navigate back

---

lib/components/study_topic_card_large.dart

Make who large CardSection clickable

Make who large CardSection clickable

---

lib/components/card_section.dart
lib/helpers/navigation_utils.dart

Add card section click analytics

Add card section click analytics

---

lib/components/season_episode_list.dart
lib/screens/episode.dart

When cur episode is clicked, scroll to top.
When any episode in episode list is clicked, autoplay.

Episode click action when episode in episode list is clicked

---

lib/graphql/queries/episode.graphql
lib/graphql/queries/episode.graphql.dart
lib/providers/playback_service.dart

Ref: https://www.notion.so/bccmedia/Send-Show-ID-to-NPAW-as-content-tvShow-160c24bb685840faa2be12d973985ee6?pvs=4

Send ShowID instead of the localized title to NPAW

---

external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/ExoPlayerController.kt
external_projects/bccm_player/lib/bccm_player_native.dart
external_projects/bccm_player/lib/bccm_player_web.dart
external_projects/bccm_player/lib/src/playback_platform_interface.dart
external_projects/bccm_player/test/bccm_player_test.dart
lib/main.dart
lib/providers/playback_service.dart
lib/providers/settings.dart

npaw/youbora needs a proper accountCode from the beginning, which means we need to setNpawConfig before we create the player, hotfixing by awaiting setNpawConfig on startup.

fix(bccm_player): hotfix for npaw initialization

---

lib/components/section_item_click_wrapper.dart
lib/components/sections/thumbnail/episode_thumbnail.dart
lib/helpers/navigation/navigation_utils.dart
lib/helpers/ui/ui_utils.dart

[Notion link](https://www.notion.so/bccmedia/Live-coming-soon-thumbnail-e07a5b6228bf4e568a143268e84b99ae)
Make sure the links for live episodes work fine:
- if live == false and locked == true =>  No link, No live tag
- If live == true and locked == true => Link to live page, Show live tag
- If live == false and locked == false => Link to episode, No live tag
- If live == true and locked == false => Link to episode, No live tag
Also fix -> Don't show wait icon when: live == true and locked == true

Fix links for live episodes

---

lib/components/featured_section.dart

Fix link for live item in featured section.

Fix link for live item in featured section

---

external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/BccmPlayerPlugin.kt

fix(android): Call stop on primarycontroller when plugin is detached from activity

---

external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/BccmPlayerPlugin.kt
external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/BccmPlayerPluginEvent.kt
external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/views/FullscreenPlayerView.kt
external_projects/bccm_player/example/pubspec.lock
external_projects/bccm_player/pubspec.yaml
pubspec.lock

fix(android): Keep playing when user locks phone

---

external_projects/bccm_player/ios/Classes/Players/AVQueuePlayerController.swift
external_projects/bccm_player/ios/Classes/Utils/LandscapeAVPlayerViewController.swift
external_projects/bccm_player/ios/Classes/Views/BccmPlayerView.swift
ios/Runner/AppDelegate.swift

Solution to [iOS - Rotate to landscape on fullscreen if locked orientation and video isnt portrait ratio](https://www.notion.so/bccmedia/iOS-Rotate-to-landscape-on-fullscreen-if-locked-orientation-and-video-isnt-portrait-ratio-1a9fffcf360342cc85c798e563dac0c1?pvs=4).
But AVFullScreenViewController is private so this hacky solution might not pass review

fix(player): experimental solution to force landscape on ios

---

lib/l10n/app_localizations.dart
lib/l10n/app_localizations_bg.dart
lib/l10n/app_localizations_da.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fi.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_hu.dart
lib/l10n/app_localizations_it.dart
lib/l10n/app_localizations_nb.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_ro.dart
lib/l10n/app_localizations_ru.dart
lib/l10n/app_localizations_sl.dart
lib/l10n/app_localizations_tr.dart
lib/l10n/intl_en.arb
lib/screens/profile/profile.dart

feat: Add link to uservoice on profile page

---

.maestro/flows/3_deep-links-public.yml
.maestro/flows/4_deep-links-bcc.yml
lib/api/brunstadtv.dart
lib/components/bottom_sheet_mini_player.dart
lib/components/episode/episode_collection.dart
lib/components/episode/episode_season.dart
lib/components/section_item_click_wrapper.dart
lib/components/sections/thumbnail_slider/item_section_thumbnail_slider.dart
lib/components/share_episode_sheet.dart
lib/graphql/queries/episode.graphql
lib/graphql/queries/episode.graphql.dart
lib/graphql/schema/schema.graphql.dart
lib/helpers/navigation/navigation_utils.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_sl.dart
lib/providers/lesson_progress_provider.dart
lib/providers/playback_service.dart
lib/router/router.dart
lib/router/router.gr.dart
lib/screens/episode.dart
test/auth/signup_test.dart

feat: episode context

---

external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/players/exoplayer/ExoPlayerController.kt

fix(android): Be able to disable the subtitles

---

lib/components/page.dart
lib/components/sections/section.dart
lib/components/sections/section_update_handler.dart

Fix issue with 'My favourites' section
- Not showing when the first episode is added to the list
- Not hiding when the list is emptied.

fix(my-list): Fix issue with 'My favourites' section not showing/hiding correctly.

---

external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/players/exoplayer/ExoPlayerController.kt

Closes #123, as this reduces bandwidth by ~90%.
This forces the lowest video bitrate to be used after no view is visible for 6 seconds. We originally used a "setRendererDisabled" function, because I expected it to stop loading video segments if you disable the renderer. But it doesn't. This is still an open issue: https://github.com/google/ExoPlayer/issues/9282, and doesn't seem plausible to fix without doing some heavy overriding of exoplayer internals.

fix(android): force lowest bitrate in audio-only mode

---

lib/components/sections/featured_section.dart

Optimize `FeaturedSection` size for tablets. (Increase height if device width > 600).
Make `_GradientImage` use the height set in `buildPageView` / `buildSlider`.

feat(featured-section): Increase height for tablets

---

lib/components/sections/icon_section.dart

Use tiles with 16:9 aspect ratio on tablets (Device width > 600)

feat(icon-section): Use tiles with 16:9 aspect ratio on tablets

---

lib/components/app_version.dart
lib/components/developer_options.dart
lib/components/onboarding/email_verification/email_verification_prompt_page.dart
lib/flavors.dart
lib/l10n/app_localizations.dart
lib/l10n/app_localizations_bg.dart
lib/l10n/app_localizations_da.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fi.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_hu.dart
lib/l10n/app_localizations_it.dart
lib/l10n/app_localizations_nb.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_ro.dart
lib/l10n/app_localizations_ru.dart
lib/l10n/app_localizations_sl.dart
lib/l10n/app_localizations_tr.dart
lib/l10n/intl_en.arb
lib/main_dev.dart
lib/main_kids_prod.dart
lib/main_prod.dart
lib/router/router.gr.dart
lib/screens/profile/about.dart
lib/screens/profile/profile.dart

feat: flavor-specific contact details, etc.

---

external_projects/bccm_player/android/src/main/java/media/bcc/bccm_player/pigeon/PlaybackPlatformApi.java
external_projects/bccm_player/android/src/main/kotlin/media/bcc/bccm_player/players/exoplayer/ExoPlayerController.kt
external_projects/bccm_player/ios/Classes/Pigeon/PlaybackPlatformApi.h
external_projects/bccm_player/ios/Classes/Pigeon/PlaybackPlatformApi.m
external_projects/bccm_player/ios/Classes/Players/AVQueuePlayerController.swift
external_projects/bccm_player/lib/src/pigeon/playback_platform_pigeon.g.dart
external_projects/bccm_player/pigeons/playback_platform_pigeon.dart
lib/flavors.dart
lib/main_kids_prod.dart
lib/providers/playback_service.dart

feat(analytics): do not send device ids

---

lib/screens/onboarding/onboarding.dart

Fix issue with sign up button not responding.
Issue was cased due to wrong context.

fix: issue with sign up button not responding

---

lib/l10n/app_localizations.dart
lib/l10n/app_localizations_bg.dart
lib/l10n/app_localizations_da.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fi.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_hu.dart
lib/l10n/app_localizations_it.dart
lib/l10n/app_localizations_nb.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_ro.dart
lib/l10n/app_localizations_ru.dart
lib/l10n/app_localizations_sl.dart
lib/l10n/app_localizations_tr.dart
lib/l10n/intl_en.arb
lib/screens/profile/profile.dart

Add 'Make a donation' button for kids app. Clicking on it launches `https://biblekids.io/<locale>/support-our-work`.

feat(profile): add 'Make a donation' button for kids app

---

lib/components/sections/thumbnail_slider/item_section_thumbnail_slider.dart

Make thumbnails responsive.
I think it would be good to also increase the font size on larger screen.

feat: Make thumbnails responsive

---

lib/components/episode/season_episode_list.dart

Make the thumbnails in the episode page responsive.

feat: Responsive thumbnails in episode page

---

pubspec.lock
pubspec.yaml

Remove dependency override for `intl` as `rudder-sdk-flutter` has fixed incompatibility.

chore: remove dependency_override

---

lib/components/next_episode_button.dart
lib/l10n/app_localizations.dart
lib/l10n/app_localizations_bg.dart
lib/l10n/app_localizations_da.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fi.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_hu.dart
lib/l10n/app_localizations_it.dart
lib/l10n/app_localizations_nb.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_ro.dart
lib/l10n/app_localizations_ru.dart
lib/l10n/app_localizations_sl.dart
lib/l10n/app_localizations_tr.dart
lib/l10n/intl_en.arb

"Next Episode" button. Waits for 5 seconds while showing progress of countdown. Executes given action when countdown is complete.
Looks like:

feat: "Next Episode" button

---

lib/components/sections/icon_grid_section.dart

Make IconGridSection responsive (Used in search page)

feat: Make icon grid section responsive

---

external_projects/bccm_player/lib/src/widgets/bccm_player.dart

Make the player in episode page scrollable / draggable.

feat: Make player scrollable / draggable

---

lib/screens/profile/profile.dart

Change donation link to paypal donation url
Fixes #412

feat(kids-donation): change donation link to paypal donation url

---

external_projects/bccm_player/lib/src/widgets/controls/default_controls.dart
external_projects/bccm_player/lib/src/widgets/mini_player/bccm_mini_player.dart
external_projects/bccm_player/lib/src/widgets/mini_player/loading_indicator.dart
external_projects/bccm_player/lib/src/widgets/video/video_player_view.dart
external_projects/bccm_player/lib/theme/bccm_player_theme.dart
external_projects/bccm_player/lib/theme/controls_theme_data.dart
external_projects/bccm_player/lib/theme/mini_player_theme_data.dart
external_projects/bccm_player/lib/theme/player_theme.dart
lib/app_root.dart
lib/components/bottom_sheet_mini_player.dart
lib/components/episode/season_episode_list.freezed.dart
lib/components/live_mini_player.dart

Make Bccm player(Player controls, Mini player) themable from app.
Fixes https://github.com/bcc-code/bcc-media-app/issues/214

feat(bccm-player): Make player themable

---

android/app/build.gradle
android/build.gradle
ios/Podfile.lock
kids/android/app/src/main/AndroidManifest.xml
kids/ios/Podfile.lock
kids/ios/Runner/Info.plist
kids/lib/components/player/player_view.dart
kids/lib/main.dart
kids/pubspec.lock
kids/pubspec.yaml
lib/api/brunstadtv.dart
lib/components/achievements/achievement_dialog.dart
lib/env/.env.dart.template
lib/env/env.dart
lib/helpers/main_js_channel.dart
lib/helpers/router/router_utils.dart
lib/main.dart
pubspec.lock
pubspec.yaml

Implemented Sentry for error tracking and reporting.
Sentry is initialized in `main.dart`, where the options also are defined.
Is there any specific features of Sentry we want to use? This initial implementation is the bare-bones implementation, where it only reports errors and crashes.

feat: add sentry for error reporting

---

kids/lib/main.dart
lib/env/.env.dart.template
lib/env/env.dart
lib/main.dart
pubspec.yaml

Adds new Sentry project to kids app

feat: use new sentry projects

---

README.md
ios/Podfile.lock
kids/pubspec.lock
lib/l10n/app_localizations.dart
lib/l10n/app_localizations_bg.dart
lib/l10n/app_localizations_da.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fi.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_hu.dart
lib/l10n/app_localizations_it.dart
lib/l10n/app_localizations_nb.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_ro.dart
lib/l10n/app_localizations_ru.dart
lib/l10n/app_localizations_sl.dart
lib/l10n/app_localizations_ta.dart
lib/l10n/app_localizations_tr.dart
pubspec.lock

Updated the `bccm-player` library to actually disable PiP mode if configured as such.
Also, I updated packages. Probably would have been smarter to do that in a separate PR

[bugfix] Prevent PiP video for shorts when backgrounding the app

---

lib/api/bmm.dart

fix: empty audio page on norwegian

---

Makefile

See the code.
Probably not useful to you, but for me its nice to just quickly make sure I'm on the latest things

add git pull of default branch to "make main-branch"

---

lib/components/shorts/short_scroll_view.dart
lib/helpers/shorts/short_analytics.dart
lib/helpers/shorts/short_controller.dart

@andreasgangso What is the reasoning behind the hard-coded delays here? 
#441 
Also, removed a ton of `debugPrint`

improve loading of shorts

---

lib/components/shorts/short_scroll_view.dart

@andreasgangso fyi, adding these back as the scrolling experience stutters without :)
We are going to investigate how to optimize in other ways, eg. see how Instagram and TikTok etc does it

fix(shorts): re-add hardcoded delay

---

lib/components/surveys/bottom_sheet_survey.dart
lib/components/surveys/survey_link.dart

I've implemented a new type of survey; links.
This can be used to send the user to external websites, eg. for scheduling interviews.
- `lib/components/surveys/survey_link.dart`
- `lib/components/surveys/bottom_sheet_survey.dart`
https://github.com/user-attachments/assets/96a6565e-2419-4099-ac8d-3669cd06a8ee

feat(surveys): wip add link survey ui

---

kids/ios/Podfile.lock
kids/lib/screens/home.dart
kids/pubspec.lock
kids/pubspec.yaml

Only the changes in `home.dart` are relevant here.
The rest of the changes are just dependency updates to get the project to run

fix(kids): refetch content after language has changed

---

kids/lib/components/settings/language_list_dialog.dart
kids/lib/components/settings/setting_list.dart
kids/lib/main.dart
kids/lib/screens/settings/content_language.dart
kids/lib/screens/settings/settings.dart
lib/helpers/constants.dart
lib/l10n/app_localizations.dart
lib/l10n/app_localizations_bg.dart
lib/l10n/app_localizations_da.dart
lib/l10n/app_localizations_de.dart
lib/l10n/app_localizations_en.dart
lib/l10n/app_localizations_es.dart
lib/l10n/app_localizations_fi.dart
lib/l10n/app_localizations_fr.dart
lib/l10n/app_localizations_hu.dart
lib/l10n/app_localizations_it.dart
lib/l10n/app_localizations_nb.dart
lib/l10n/app_localizations_nl.dart
lib/l10n/app_localizations_pl.dart
lib/l10n/app_localizations_pt.dart
lib/l10n/app_localizations_ro.dart
lib/l10n/app_localizations_ru.dart
lib/l10n/app_localizations_sl.dart
lib/l10n/app_localizations_ta.dart
lib/l10n/app_localizations_tr.dart
lib/l10n/bccm_en.arb
lib/providers/graphql.dart
lib/providers/settings.dart
lib/providers/settings.freezed.dart

You can ignore the changes in the `/l10n` directory

feat(kids): add content with preferred languages setting
